/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 */
public with sharing class GD_SignatureEnvelopeFieldLocationSetting {

	public Integer page { get; set; }
	public Double locationX { get; set; }
	public Double locationY { get; set; }
	public Double locationWidth { get; set; }
	public Double locationHeight { get; set; }
	public String fontName { get; set; }
	public String fontColor { get; set; }
	public Double fontSize { get; set; }
	public Boolean fontBold { get; set; }
	public Boolean fontItalic { get; set; }
	public Boolean fontUnderline { get; set; }
	public Boolean forceNewField { get; set; }
	public Integer align { get; set; }
	

}

